services:
  mongodb:
    image: mongo:7.0.14
    restart: on-failure:15
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./.infra/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh:ro
      - ./.volumes/mongodb/db:/data/db
      - ./.volumes/mongodb/configdb:/data/configdb
    command: "--replSet rs0 --keyFile /data/configdb/mongo-keyfile --bind_ip_all --port 27017"

  mongodb-init:
    image: mongo:7.0.14
    restart: on-failure:15
    env_file:
      - .env
    environment:
      HOSTNAME: mongodb
      ROOT_DB: ${MONGO_INIT_DB}
      ROOT_USER: ${MONGO_ROOT_USERNAME}
      ROOT_PASS: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./.infra/replicaset-init.sh:/mongo-replicaset-init.sh:ro
    links:
      - mongodb
    depends_on:
      - mongodb
    command: /bin/bash /mongo-replicaset-init.sh
